<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Program PERSITA MEMBER</name>
   <tag></tag>
   <elementGuidId>7d45b4e2-ea01-416c-9bd1-9048f1c69345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalTnc']/div/div/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>cd28e756-00a2-4564-9e2d-23c7aa73bdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program PERSITA MEMBER</value>
      <webElementGuid>fff6ea94-498d-44c3-acd9-56d014251e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalTnc&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content pta-modal&quot;]/div[@class=&quot;modal-body m-lg-3 m-sm-2&quot;]/h5[1]</value>
      <webElementGuid>d419ebae-34b3-49ff-97a5-72a9300e731d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalTnc']/div/div/div/h5</value>
      <webElementGuid>8c57662d-3b6a-4c29-ad2e-abe2ac712647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali ke Halaman Home'])[1]/following::h5[1]</value>
      <webElementGuid>cb693c51-644e-48ae-b7f5-18f4cdbe91d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[2]/following::h5[1]</value>
      <webElementGuid>2cc8b3f9-b0e0-494a-9b15-34eef93046e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan'])[1]/preceding::h5[1]</value>
      <webElementGuid>c27fb006-78b9-4c5f-acbf-ad32159b46fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>38f92e14-938c-48a6-acd7-04055e9d5d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Program PERSITA MEMBER' or . = 'Program PERSITA MEMBER')]</value>
      <webElementGuid>8c665497-4793-4ef4-8031-d158a2573ee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
