<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No KTP_identity_number</name>
   <tag></tag>
   <elementGuidId>f3ee9e4c-47d6-4ed1-a9bd-a85531e057d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ktp_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ktp_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0dac7c0-2ddf-4630-8642-e2cbee74c9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ff989f4-7155-4baa-8528-f248dd46b9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pta-form__input</value>
      <webElementGuid>b362775e-7bb3-4036-b9ec-89506a55d265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identity_number</value>
      <webElementGuid>ab65c419-c622-4c0d-844e-e2ba6a5400bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ktp_number</value>
      <webElementGuid>2d6b54c0-27aa-4b12-bafa-85fc5f2306ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Lengkap KTP</value>
      <webElementGuid>4f4535d6-ec44-4aa9-af2d-4ea73d1107a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>7b1c4f4a-4892-4394-a24a-a8d1b5be3bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ktp_number&quot;)</value>
      <webElementGuid>aef4df98-701b-49ec-a641-3b07cf5de459</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ktp_number']</value>
      <webElementGuid>de2e0480-1a2f-48ac-bdaa-558ca7f90697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signUpValidate']/div[4]/div[2]/div/input</value>
      <webElementGuid>c8ea9bf1-40d8-4665-8676-a480fecc6ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6cac4df3-0782-4394-8ded-7c39b326eb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'identity_number' and @id = 'ktp_number' and @placeholder = 'Nomor Lengkap KTP']</value>
      <webElementGuid>8ecf16f7-0aea-44bb-aa8c-37dcb0ceb1c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
