<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Pria</name>
   <tag></tag>
   <elementGuidId>fa5cf408-e892-40b8-8203-61e22108af69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signUpValidate']/div[5]/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.custom-control-label.pta-form__control-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8f6831c9-171d-449d-9781-b68f548a6dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label pta-form__control-label</value>
      <webElementGuid>c04d5087-8aff-4110-bd0f-61eb06b3f175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gender_1</value>
      <webElementGuid>bb2239ef-788f-4326-9b60-b4a6c6a5b4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pria</value>
      <webElementGuid>2dbc770a-4eed-4f49-b706-21e144b38efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signUpValidate&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;custom-control custom-radio custom-control-inline&quot;]/label[@class=&quot;custom-control-label pta-form__control-label&quot;]</value>
      <webElementGuid>aedba18b-9646-4430-867c-41d4b6db1702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signUpValidate']/div[5]/div/div/label</value>
      <webElementGuid>9d550b82-0de7-4129-abde-635d393fa929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin'])[1]/following::label[1]</value>
      <webElementGuid>f463362f-8756-4b7c-9d70-a7c060996dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No KTP'])[1]/following::label[2]</value>
      <webElementGuid>2a6ab359-5e2c-4b36-a5ad-d142ba93e586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wanita'])[1]/preceding::label[1]</value>
      <webElementGuid>317bc7ec-b752-4763-86bf-838810f6b76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Lahir'])[1]/preceding::label[2]</value>
      <webElementGuid>fb5b1937-c42e-470d-a075-99df6ffdfead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pria']/parent::*</value>
      <webElementGuid>e93db031-02e4-4666-be15-76177852c30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/label</value>
      <webElementGuid>516e82e1-9205-40bd-9bd7-56f521a766f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Pria' or . = 'Pria')]</value>
      <webElementGuid>34d39632-b724-4fe5-b430-6ec3bd012f47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
