<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tanggal Lahir_pta-form__with-action__i_131b93</name>
   <tag></tag>
   <elementGuidId>0df75c00-99ad-4775-a586-0650563ef0f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signUpValidate']/div[6]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pta-form__with-action__icon.ic-form__calendar.trigger-datepicker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>185e80f3-99ee-4ae2-aa1c-ebe229b526f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pta-form__with-action__icon ic-form__calendar trigger-datepicker</value>
      <webElementGuid>d1d347ab-d050-4899-90ba-ca9ab8940c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signUpValidate&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;pta-form__with-action&quot;]/span[@class=&quot;pta-form__with-action__icon ic-form__calendar trigger-datepicker&quot;]</value>
      <webElementGuid>72487d52-57f6-4d37-94b3-da8d1837c5c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signUpValidate']/div[6]/div/span</value>
      <webElementGuid>31b6326a-c5fc-448e-9ecc-40f0ae2aa383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span</value>
      <webElementGuid>6797c842-d4a6-4aef-8d3b-332042e8fc06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
